---

- name: Add bash dotfile
  copy: src=bash.dotfile dest=~/.dotfiles/ mode=0644

- name: Arch | Add linux dotfile
  copy: src=linux.dotfile dest=~/.dotfiles/ mode=0644
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

- name: Add git dotfile
  copy: src=git.dotfile dest=~/.dotfiles/ mode=0644

- name: Add .gitconfig
  copy: src=.gitconfig dest=~/ mode=0644
