---

- include: dotfiles.yml
- include: homebrew.yml
  when: ansible_os_family == 'Darwin'
- include: tools.yml
  
- name: Ensure everything in ~/.dotfiles/ is sourced in ~/.bash_profile
  lineinfile: dest=~/.bashrc create=yes line='for file in ~/.dotfiles/*.dotfile; do if [ -f "$file" ]; then . $file; fi; done'

- name: Copy ssh config
  copy: src=config.ssh dest=~/.ssh/config mode=0600
  
