---
- name: Arch | Install applications
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - hub
    - screen
    - terminator
    - wget
    - xclip
      #- google-chrome #Need to find method for AUR install
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'
