---
- name: Arch | Install atom
  pacman: name=atom state=latest update_cache=yes
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

- name: Check if atom is installed
  command: which atom
  register: atom_is_installed
  ignore_errors: yes

# apm command source - https://github.com/hnakamur/ansible-role-atom-packages
- name: Install atom packages
  apm: name={{item}} state=latest
  with_items:
    - ansible-snippets
    - auto-indent
    - busy-signal
    - git-plus
    - intentions
    - language-docker
    - language-terraform
    - language-ansible
    - linter
    - linter-ansible-syntax
    - linter-js-yaml
    - linter-ui-default
    - linter-shellcheck
    - markdown-pdf
    - markdown-writer
    - minimap
    - minimap-git-diff
    - script
  when: atom_is_installed.rc == 0
