- name: Arch | Install applications
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - aws-cli 

- name: Add aws dotfile 
  copy: src=aws.dotfile dest=~/.dotfiles/ mode=0644

