---
- name: Arch | Install dev-tools applications
  pacman:
    name:
      - git
      - vim
      - jq
      - httpie
      - bind-tools
    state: latest
    update_cache: yes
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

# - include: atom.yml
- include: python.yml
- include: haskell.yml
- include: git-prompt.yml
- include: gcloud.yml
- include: aws.yml
- include: azure.yml
- include: kubernetes.yml
# - include: virtualbox-vagrant.yml

- name: Ensure everything in ~/.dotfiles/ is sourced in ~/.bash_profile
  lineinfile: dest=~/.bashrc create=yes line='for file in ~/.dotfiles/*.dotfile; do if [ -f "$file" ]; then . $file; fi; done'
