- name: Arch | Install applications
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-pip
    - python2-pip
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'
