---
- name: Arch | Install vagrant applications
  pacman:
    name:
      - virtualbox
      - vagrant
    state: latest
    update_cache: yes
  become: true
  when: ansible_os_family == 'Archlinux' or ansible_os_family == 'Manjaro Linux'

- name: Add vagrant templte
  copy: src=Vagrantfile.template dest=~/.dotfiles/ mode=0644

- name: Add vagrant dotfile
  copy: src=vagrant.dotfile dest=~/.dotfiles/ mode=0644
